/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef entry_thrift_CONSTANTS_H
#define entry_thrift_CONSTANTS_H

#include "entry_thrift_types.h"

namespace entry {

class entry_thriftConstants {
 public:
  entry_thriftConstants();

};

extern const entry_thriftConstants g_entry_thrift_constants;

} // namespace

#endif
