/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "entry_thrift_constants.h"

namespace entry {

const entry_thriftConstants g_entry_thrift_constants;

entry_thriftConstants::entry_thriftConstants() {
}

} // namespace

